- defaults:
    link:
      relink: true
      create: true
      glob: true
    shell:
        stdout: true
        stderr: true

- clean: ["~"]

- link:
    ~/.aliases: config/.aliases
    ~/.functions: config/.functions
    ~/.bash_profile: config/.bash_profile
    ~/.gitconfig: config/.gitconfig
    ~/.hammerspoon: config/.hammerspoon
    ~/.vim: config/.vim
    ~/.vimrc: config/.vimrc
    ~/.gvimrc: config/.gvimrc
    ~/.zshrc: config/.zshrc
    ~/.p10k.zsh: config/.p10k.zsh
    ~/Library/Application Support/SourceTree/actions.plist: config/sourcetree/actions.plist

- shell:
    - scripts/essentials.sh
    - scripts/brews.sh
    - scripts/cask.sh
    - scripts/apps.sh
