- defaults:
    link:
      relink: true
      create: true
      glob: true
    shell:
        stdout: true
        stderr: true

- clean: ["~"]

- link:
    ~/.bash_profile: config/.bash_profile
    ~/.gitconfig: config/.gitconfig

- shell:
    - tools/homebrew.sh
