- defaults:
    link:
      relink: true
      create: true
      glob: true
    shell:
        stdout: true
        stderr: true

- clean: ["~"]

- link:
    ~/.aliases: config/.aliases
    ~/.functions: config/.functions
    ~/.bash_profile: config/.bash_profile
    ~/.gitconfig: config/.gitconfig
    ~/.hammerspoon: config/.hammerspoon

- shell:
    - scripts/essentials.sh
    - scripts/brews.sh
    - scripts/cask.sh
    - scripts/apps.sh
