- defaults:
    link:
      relink: true
      create: true
      glob: true
    shell:
        stdout: true
        stderr: true

- clean: ["~"]

- link:
    ~/.aliases: config/.aliases
    ~/.functions: config/.functions
    ~/.bash_profile: config/.bash_profile
    ~/.gitconfig: config/.gitconfig

- shell:
    - scripts/brew.sh
    - scripts/tools.sh
    - scripts/cask.sh
